export const recordedSessions = [
    { id: "dU6JY136vTg", duration: 15, title: "Opening Remarks", published: "10:00am" },
    { id: "R_CTelKp320", duration: 30, title: "Showcasing Xplore with James Neale", published: "10:15am" },
    { id: "D26D5djayYI", duration: 30, title: "Performance Tuning with Pawan Kumar Singh", published: "10:15am" },
    { id: "u5UN53t_LkM", duration: 15, title: "Avoiding Data Migration Pitfalls with Slava Savitsky", published: "10:45am" },
    { id: "IcoUhnoQoiY", duration: 15, title: "Showcasing Health Sentinel with Maik Skoddow", published: "10:45am" },
    { id: "NdZQxb_vtiI", duration: 15, title: "Being a Good ServiceNow Dev with Ekta Sharma", published: "11:00am" },
    { id: "jJPNIrXe4Lk", duration: 15, title: "Turning Data into Trust: The Role of Data Certification with Shreya Wani", published: "11:00am" },
    { id: "3860UkCIepg", duration: 15, title: "2 Week Upgrades with Chris Schuh", published: "11:15am" },
    { id: "xC_qxPKFJm8", duration: 30, title: "Modern Web Development in ServiceNow with Andrew Pischulin", published: "11:30am" },
    { id: "NM06lBC5Dxk", duration: 30, title: "Showcasing SNUtils with Arnoud Kooi", published: "11:30am" },
    { id: "uCsnTHfsDYE", duration: 15, title: "Microsoft Graph API without IntegationHub with Anvesh Kumar Mupparaju", published: "12:00pm" },
    { id: "KD2TQNrABZk", duration: 15, title: "ReleaseOps: Confident QC & Automated Releases in ServiceNow with Robert Fedoruk", published: "12:00pm" },
    { id: "CnILTeGW50g", duration: 30, title: "How is CRM different from S2P and what features come from AI with Shanma Negi", published: "12:15pm" },
    { id: "bqxEgz5gBh8", duration: 30, title: "Best Practices for HRSD with Sabrina Ethridge", published: "12:30pm" },
    { id: "hhsr2rOCalE", duration: 15, title: "A11y and Localization Features in NowAssist + Free Open Source Tool with Alaina Beaver", published: "12:30pm" },
    { id: "CrVeL8kFZ7w", duration: 15, title: "Jumpstart AI with Mo Fagir", published: "2:00pm" },
    { id: "0kEVWwlKvgY", duration: 15, title: "Beating the Complexity of Approval Flows with Jan Procházka", published: "2:00pm" },
    { id: "EsIBWaqS7Z8", duration: 15, title: "Why Foundational Data for AI with Gregory Yuh", published: "2:15pm" },
    { id: "BfHBHE81t-Q", duration: 15, title: "The Silent Killer: How Poor Governance Breaks Your Platform with Dr.Atul Grover", published: "2:15pm" },
    { id: "Ck1_O-9Nq5U", duration: 15, title: "Showcasing SNDEVTOOLS by Jai Babbar", published: "2:30pm" },
    { id: "e0ZyEY-Hfhg", duration: 15, title: "Keeping ServiceNow platform healthy with Swapna Abburi", published: "2:30pm" },
    { id: "EhwuEUeCmfc", duration: 15, title: "Practical Technical Governance with Jacques Clement", published: "2:45pm" },
    { id: "PqXMEEVELKY", duration: 15, title: "Tracking AI Spend using Cloud Cost Management (CCM) with Ian Cahall", published: "2:45pm" },
    { id: "Sp0KbdMF2_c", duration: 15, title: "Beyond the Basics: UI Builder Tricks for Workspace Customizations you're missing with Jillian Howell", published: "3:00pm" },
    { id: "F-YVb0CTnVU", duration: 15, title: "ServiceNow Mobile App Builder: Use Cases and Workarounds for Input Form Screens with Jean Emmanual", published: "3:00pm" },
    { id: "Qu3qaekUWjs", duration: 15, title: "ServiceNow Studio with Ishaan Shoor", published: "3:30pm" },
    { id: "1RQHPa23iR8", duration: 15, title: "Creator Catalyst: Human Centered Design + Agile with Michael Slabodnick", published: "3:30pm" },
    { id: "eVvCRg86hIo", duration: 15, title: "Flexible Flows using Decision Builder and Dynamic Flow Launcher with Dan Menter", published: "3:30pm" },
    { id: "eAjt2FbS3j0", duration: 15, title: "Freelancing to get your in on ServiceNow with Mike Roberts", published: "3:45pm" },
    { id: "K8crp6Vlcpc", duration: 15, title: "Better User Experience using AI with Ritesh Dalal", published: "3:45pm" },
    { id: "knUqfCuOhkw", duration: 15, title: "ServiceNow Protection Policies - Protecting Your Intellectual Property with Ty Roach", published: "4:00pm" },
    { id: "K4Dd1weTET0", duration: 15, title: "Things to do with Many to Many tables in Servicenow by Chuck Tomasi", published: "4:00pm" },
    { id: "H9cpET2csVs", duration: 15, title: "Reporting using Platform Analytics with Rafael Cardoso", published: "4:15pm" },
    { id: "Zws3iz84l6s", duration: 15, title: "Pro-code Performance Missedsteaks & Omissons with Tim Woodruff", published: "4:15pm" },
    { id: "THlKFi5Gtgw", duration: 15, title: "Fred's Final Business Rule with Kevin Clark", published: "4:30pm" },
    { id: "G-wn7WYRYe8", duration: 15, title: "From Chaos to Clarity Employee Center with Sarah Toulson", published: "4:30pm" },
    { id: "I3hwsT1tD48", duration: 15, title: "Closing Remarks", published: "4:45pm" }
];

export default recordedSessions;