export const recordedSessions = [
    { id: "dU6JY136vTg", duration: 15, published: "10:00am", title: "Opening Remarks", speakers: ["Jace Benson", "Carleen Carter", "Justin Meadows", "Chuck Tomasi"] },
    { id: "R_CTelKp320", duration: 30, published: "10:15am", title: "Showcasing Xplore", speakers: ["James Neale"] },
    { id: "D26D5djayYI", duration: 30, published: "10:15am", title: "Performance Tuning", speakers: ["Pawan Kumar Singh"] },
    { id: "u5UN53t_LkM", duration: 15, published: "10:45am", title: "Avoiding Data Migration Pitfalls", speakers: ["Slava Savitsky"] },
    { id: "IcoUhnoQoiY", duration: 15, published: "10:45am", title: "Showcasing Health Sentinel", speakers: ["Maik Skoddow"] },
    { id: "NdZQxb_vtiI", duration: 15, published: "11:00am", title: "Being a Good ServiceNow Dev", speakers: ["Ekta Sharma"] },
    { id: "jJPNIrXe4Lk", duration: 20, published: "11:00am", title: "Turning Data into Trust: The Role of Data Certification", speakers: ["Shreya Wani"] },
    { id: "3860UkCIepg", duration: 15, published: "11:15am", title: "2 Week Upgrades", speakers: ["Chris Schuh"] },
    { id: "xC_qxPKFJm8", duration: 30, published: "11:30am", title: "Modern Web Development in ServiceNow", speakers: ["Andrew Pischulin"] },
    { id: "NM06lBC5Dxk", duration: 30, published: "11:30am", title: "Showcasing SNUtils", speakers: ["Arnoud Kooi"] },
    { id: "uCsnTHfsDYE", duration: 15, published: "12:00pm", title: "Microsoft Graph API without IntegationHub", speakers: ["Anvesh Kumar Mupparaju"] },
    { id: "KD2TQNrABZk", duration: 15, published: "12:00pm", title: "ReleaseOps: Confident QC & Automated Releases in ServiceNow", speakers: ["Robert Fedoruk"] },
    { id: "CnILTeGW50g", duration: 30, published: "12:15pm", title: "How is CRM different from S2P and what features come from AI", speakers: ["Shanma Negi"] },
    { id: "bqxEgz5gBh8", duration: 30, published: "12:30pm", title: "Best Practices for HRSD", speakers: ["Sabrina Ethridge"] },
    { id: "hhsr2rOCalE", duration: 30, published: "12:30pm", title: "A11y and Localization Features in NowAssist + Free Open Source Tool", speakers: ["Alaina Beaver"] },
    { id: null,          duration: 60, published: "1:00pm", title: "Networking", speakers: ["You"] },
    { id: "CrVeL8kFZ7w", duration: 15, published: "2:00pm", title: "Jumpstart AI", speakers: ["Mo Fagir"] },
    { id: "0kEVWwlKvgY", duration: 15, published: "2:00pm", title: "Beating the Complexity of Approval Flows", speakers: ["Jan Procházka"] },
    { id: "EsIBWaqS7Z8", duration: 15, published: "2:15pm", title: "Why Foundational Data for AI", speakers: ["Gregory Yuh"] },
    { id: "BfHBHE81t-Q", duration: 15, published: "2:15pm", title: "The Silent Killer: How Poor Governance Breaks Your Platform", speakers: ["Dr.Atul Grover"] },
    { id: "Ck1_O-9Nq5U", duration: 15, published: "2:30pm", title: "Showcasing SNDEVTOOLS", speakers: ["Jai Babbar"] },
    { id: "e0ZyEY-Hfhg", duration: 15, published: "2:30pm", title: "Keeping ServiceNow platform healthy", speakers: ["Swapna Abburi"] },
    { id: "EhwuEUeCmfc", duration: 15, published: "2:45pm", title: "Practical Technical Governance", speakers: ["Jacques Clement"] },
    { id: "PqXMEEVELKY", duration: 15, published: "2:45pm", title: "Tracking AI Spend using Cloud Cost Management (CCM)", speakers: ["Ian Cahall"] },
    { id: "Sp0KbdMF2_c", duration: 30, published: "3:00pm", title: "Beyond the Basics: UI Builder Tricks for Workspace Customizations you're missing",  speakers: ["Jillian Howell"] },
    { id: "F-YVb0CTnVU", duration: 30, published: "3:00pm", title: "ServiceNow Mobile App Builder: Use Cases and Workarounds for Input Form Screens", speakers: ["Jean Emmanual"] },
    { id: "Qu3qaekUWjs", duration: 15, published: "3:30pm", title: "ServiceNow Studio", speakers: ["Ishaan Shoor"] },
    { id: "1RQHPa23iR8", duration: 15, published: "3:30pm", title: "Creator Catalyst: Human Centered Design + Agile",   speakers: ["Michael Slabodnick"] },
    { id: "eVvCRg86hIo", duration: 15, published: "3:30pm", title: "Flexible Flows using Decision Builder and Dynamic Flow Launcher", speakers: ["Dan Menter"] },
    { id: "eAjt2FbS3j0", duration: 15, published: "3:45pm", title: "Freelancing to get your in on ServiceNow", speakers: ["Mike Roberts"] },
    { id: "K8crp6Vlcpc", duration: 15, published: "3:45pm", title: "Better User Experience using AI", speakers: ["Ritesh Dalal"] },
    { id: "knUqfCuOhkw", duration: 15, published: "4:00pm", title: "ServiceNow Protection Policies - Protecting Your Intellectual Property", speakers: ["Ty Roach"] },
    { id: "K4Dd1weTET0", duration: 15, published: "4:00pm", title: "Things to do with Many to Many tables in Servicenow by Chuck Tomasi", speakers: ["Chuck Tomasi"] },
    { id: "H9cpET2csVs", duration: 15, published: "4:15pm", title: "Reporting using Platform Analytics with Rafael Cardoso", speakers: ["Rafael Cardoso"] },
    { id: "Zws3iz84l6s", duration: 15, published: "4:15pm", title: "Pro-code Performance Missedsteaks & Omissons", speakers: ["Tim Woodruff"] },
    { id: "THlKFi5Gtgw", duration: 15, published: "4:30pm", title: "Fred's Final Business Rule", speakers: ["Kevin Clark"] },
    { id: "G-wn7WYRYe8", duration: 15, published: "4:30pm", title: "From Chaos to Clarity Employee Center", speakers: ["Sarah Toulson"] },
    { id: "I3hwsT1tD48", duration: 15, published: "4:45pm", title: "Closing Remarks", speakers: ["Jace Benson","Carleen Carter", "Chuck Tomasi", "Jeff Jessie"] }
];

export default recordedSessions;